# This is a basic workflow to help you get started with Actions

name: Destroy

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    id-token: write
    contents: read
    packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: 'Install Azure Function Core Tools'
        run: 'npm i -g azure-functions-core-tools@3'

      - name: HashiCorp - Setup Terraform
        # You may pin to the exact commit or the version.
        # uses: hashicorp/setup-terraform@d22444889af304a44b997011fbabb81ff705a7b4
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: latest

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KV_NAME }}
          secrets: 'container-name, resource-group-name, storage-account-name, subscription-id, ARM-TENANT-ID, ARM-CLIENT-ID'  # comma separated list of secret keys that need to be fetched from the Key Vault 
        id: kvAction

      - name: plan terraform
        env:
          ARM_CLIENT_ID: ${{ steps.kvAction.outputs.ARM-CLIENT-ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
          ARM_TENANT_ID: ${{ steps.kvAction.outputs.ARM-TENANT-ID }}
          TF_VAR_container_name: ${{ steps.kvAction.outputs.container-name }}
          TF_VAR_resource_group_name: ${{ steps.kvAction.outputs.resource-group-name }}
          TF_VAR_storage_account_name: ${{ steps.kvAction.outputs.storage-account-name }}
          TF_VAR_subscription_id: ${{ steps.kvAction.outputs.subscription-id }}
          TF_VAR_key: ${{ github.repository }}.tfstate
          TF_VAR_gh_repo: ${{ github.repository }}
        run: |
            echo "starting..."
            cd terraform
            ./env_setup.sh
            terraform init --backend-config=backend.tfvars
            terraform plan -out theplan

      - name: apply terraform
        env:
          ARM_CLIENT_ID: ${{ steps.kvAction.outputs.ARM-CLIENT-ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
          ARM_TENANT_ID: ${{ steps.kvAction.outputs.ARM-TENANT-ID }}
          TF_VAR_container_name: ${{ steps.kvAction.outputs.container-name }}
          TF_VAR_resource_group_name: ${{ steps.kvAction.outputs.resource-group-name }}
          TF_VAR_storage_account_name: ${{ steps.kvAction.outputs.storage-account-name }}
          TF_VAR_subscription_id: ${{ steps.kvAction.outputs.subscription-id }}
          TF_VAR_key: ${{ github.repository }}.tfstate
          TF_VAR_gh_repo: ${{ github.repository }}
        run: |
            echo "starting..."
            cd terraform
            terraform destroy -auto-approve
